### ISSUE TITLE
(Active) BLE scan

### ISSUE THREAD

**Issue by michapr** [enesbcs/mpyeasy#1]
Hi,

great, that version is public now! ;)

And nice that BLE scan is working now!
Can it be possible in future to show device name to understand what device is it in table?

Thanks!
Michael

**Comment by enesbcs** [comment]
At this time only passive scan works in micropython, but for name resolution active scanning is necessary.

According this issue active scanning is available, however i've got empty results with active scanning now. :(
https://github.com/micropython/micropython/pull/6300

**Comment by michapr** [comment]
not sure of course, but maybe because of this it is still passive scan?
/src/inc/ubtle.py
```
    def scan(self, timeout=10, passive=True):
        self.clear()
        self.start(timeout,passive=passive)
        self.process()
        self.stop()
        return self.getDevices()
```

**Comment by enesbcs** [comment]
As i said i've tested active scanning and returned empty results. With my development version of course... you can change passive=True to passive=False and see yourself.

**Comment by enesbcs** [comment]
Finally i've found the error: in current micropython version only positional arguments accepted by BLE.gap_scan. In next mpyeasy release BLE scanning will be active in the Tools menu.

**Comment by enesbcs** [comment]
Supported in v1.0.007
