### ISSUE TITLE
OTA update

### ISSUE THREAD

**Issue by michapr** [enesbcs/mpyeasy#2]
Can confirm that OTA is working fine - even if progress bar show only 0% and 100% ;) 

But in my case ESP did not reboot after update - is it by design?

Thanks,
Michael

**Comment by enesbcs** [comment]
OTA is supported from 1.0.3 earlier alpha builds did not contain that.

Yes, if the upload was succesful, the Reboot button has to be pressed. 
I had a previous issue with endless reboot loop, so i think reboot will be fine manually.
