### ISSUE TITLE
DS3231 RTC not working

### ISSUE THREAD

**Issue by laci222** [enesbcs/mpyeasy#4]
Hi 

Thanks for your amazing job. 
I tried to connect a DS3231 RTC module, but the device does not use it. When there is a wifi connection, the current time is set using NTP, but when the device boots without network, the current time resets to 2000/01/01 even if the RTC is connected. 
The I2C line is enabled, I2C scan detects the device, but doesn't use it. 
![image](https://user-images.githubusercontent.com/12460666/99727155-d53f2880-2ab7-11eb-9dd6-0f3927e4a2cc.png)
Is it a bug, or I use it incorrectly?

**Comment by enesbcs** [comment]
Do you use 1.0.5 version? Before that version, it was an error in the rtc init process. Do you see any errors in the Log (Debug level) on startup?

**Comment by enesbcs** [comment]
Battery is fine in the DS3231? I've tested it and it works in 1.0.005.
[![Log](https://i.ibb.co/H2TM7fx/ds3231.jpg)](https://ibb.co/H2TM7fx)

**Comment by laci222** [comment]
I destroyed my node-mcu, so I can't try it now until my new one arrives. I've tried it with version 1.0.0.4 only, so I think it will be ok with this new version. 
My rtc was fully charged and functional.
