### ISSUE TITLE
How to enable PSRAM on ESP32-WROVER-B

### ISSUE THREAD

**Issue by henkiejan1** [enesbcs/mpyeasy#8]
Hi,

I want as you suggested enable PSRAM for my ESP32 WROVER-B module with 8MB PSRAM. But i don't understand how to enable. I tried to set PSRAM-CS to GPIO16 and PSRAM-CLK to GPIO17 but it did not detected anything. 

Could you help me please?

Thank you!

**Comment by enesbcs** [comment]
PSRAM is automatically enabled if exists on the board, as support is compiled into mPyEasy firmware.
Please double check your module type. Some chinese sellers sells WROOM modules as WROVER... but it will not have PSRAM.

You can try it yourself flashing pure PSRAM enabled micropython on your board:

https://micropython.org/resources/firmware/esp32spiram-idf3-20210202-v1.14.bin

Than executing these two commands in REPL (with Thonny):

```
import gc
gc.mem_free()

```
If it is saying ~110kb free RAM, you have no PSRAM at all.

**Comment by henkiejan1** [comment]
It says:
`>>> gc.mem_free()
4096864
`

So it has PSRAM i think?

**Comment by enesbcs** [comment]
Yes, it has! And what do you see on the system info page, when you are using mPyEasy?

**Comment by henkiejan1** [comment]
Not supported. Also in the start log. But with version 0.5 it works. So maybe a bug in  0.6?

**Comment by enesbcs** [comment]
It is possible, I'd used another micropython core for 0.6. I will compile the next mpyeasy against latest micropython 1.14.

**Comment by enesbcs** [comment]
mPyEasy 1.007 added to releases https://github.com/enesbcs/mpyeasy/releases
Tested with TTGO WROVER module with 4MB PSRAM.

**Comment by henkiejan1** [comment]
New version works also! :)

**Comment by enesbcs** [comment]
Closed as solved
